name: Bot Pure Bluesky

on:
  schedule:
    - cron: "0 * * * *"  # a cada 1 hora
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: pip install atproto feedparser

      - name: Rodar bot
        run: python -m program.bot.botsky
        env:
          BSKY_USER: ${{ secrets.BSKY_USER }}
          BSKY_PASS: ${{ secrets.BSKY_PASS }}
